create bootstrap project
xavierjeanne/OC_Blog pull request #10
Opened 2020-02-04 15:01 UTC by xavierjeanne

Pull request for issues Bootstrap project

2020-02-04 15:21 UTC, xavierjeanne commented
#9

2020-02-05 16:05 UTC, aguidis requested changes
quelques retours mais bon boulot sinon :)

2020-02-05 16:05 UTC, aguidis commented on src/Blog/BlogModule.php
> +
supprimer les lignes supplémentaires

2020-02-05 16:05 UTC, aguidis commented on src/Blog/BlogModule.php
> +
same

2020-02-05 16:05 UTC, aguidis commented on src/Blog/BlogModule.php
> +
supprimer les lignes supplémentaires

2020-02-05 16:05 UTC, aguidis commented on src/Blog/BlogModule.php
> +
same

2020-02-05 16:05 UTC, aguidis commented on src/Blog/Controller/BlogController.php
> +
2 lignes ici

2020-02-05 16:05 UTC, aguidis commented on src/Blog/Controller/BlogController.php
> +    /**
ce bloc de doc n'apporte pas plus d'information que le typage déjà présent

2020-02-05 16:05 UTC, aguidis commented on src/Blog/Controller/BlogController.php
> +    public function __invoke(ServerRequestInterface $request)
rajouter le typage de retour `public function __invoke(ServerRequestInterface $request): void` et supprimer le bloc d'annotation

2020-02-05 16:05 UTC, aguidis commented on src/Blog/Controller/BlogController.php
> +    public function index(ServerRequestInterface $request): string
Si ce controlleur va afficher la page d'accueil je te suggère de le renommer `HomepageController`

Le but est d'avoir un controlleur par page afin d'éviter des controlleurs de 1000 lignes

Quelle est la différence ici entre la méthode `_invoke()` et `index()` ?
Si on peut juste avoir une méthode `__invoke()`, qui fait tout le travail de récupération des infos avant de renvoyer un templat, par controlleur ce serait propre

2020-02-05 16:05 UTC, aguidis commented on src/Framework/App.php
> +
ligne en trop

2020-02-05 16:05 UTC, aguidis commented on src/Framework/App.php
> +    /**
supprimer ce bloc de doc

2020-02-05 16:05 UTC, aguidis commented on src/Framework/App.php
> +
lignes à supprimer

2020-02-05 16:05 UTC, aguidis commented on src/Framework/Middleware/CallableMidlleware.php
> +     * process an incoming server request and return a response
tu peux laisser ce commentaire mais tu peux supprimer le reste

2020-02-05 16:05 UTC, aguidis commented on src/Framework/Middleware/CallableMidlleware.php
> +
lignes en trop

2020-02-05 16:05 UTC, aguidis commented on src/Framework/Renderer/RendererInterface.php
> +
pareil

2020-02-05 16:05 UTC, aguidis commented on src/Framework/Renderer/RendererInterface.php
> +     * @param string $namespace
supprimer les `@param` de ce fichier car tu types tout déjà

2020-02-05 16:05 UTC, aguidis commented on src/Framework/Renderer/TwigRenderer.php
> +     * @param string $view
supprimer les @param/@return de ce fichier car tu types tout déjà

2020-02-05 16:05 UTC, aguidis commented on src/Framework/Renderer/TwigRendererFactory.php
> +
ligne en trop

2020-02-05 16:05 UTC, aguidis commented on src/Framework/Repository.php
> + * class method use for repository
je ne comprends pas ce commentaire

2020-02-05 16:05 UTC, aguidis commented on src/Framework/Repository.php
> +     * @return array
Supprimer les `@param ou les @return` de ce fichier

2020-02-05 16:05 UTC, aguidis commented on src/Framework/Route.php
> + * represent a matched route
Supprimer les  lignes en trop de ce fichier

2020-02-06 06:44 UTC, aguidis approved these changes

2020-02-06 06:50 UTC, merged